# Generated by Django 4.0.4 on 2022-05-07 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_url', models.URLField(max_length=1000)),
                ('product_url_created_at', models.DateField(auto_now_add=True)),
                ('product_url_image', models.URLField(max_length=1000)),
                ('store_url', models.URLField(max_length=1000)),
                ('consult_date', models.DateField()),
                ('total_vendas', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Produtos',
                'db_table': 'Produto',
                'ordering': ['consult_date', 'total_vendas'],
            },
        ),
    ]
